export const FieldOfStudy = {
  ADMINISTRATION: 'ADMINISTRATION',
  ARTS_DESIGN: 'ARTS_DESIGN',
  BUSINESS_MANAGEMENT: 'BUSINESS_MANAGEMENT',
  COMMUNICATION: 'COMMUNICATION',
  COMPUTER_SCIENCE: 'COMPUTER_SCIENCE',
  DATA_ANALYTICS: 'DATA_ANALYTICS',
  ENGINEERING: 'ENGINEERING',
  FINANCE_ACCOUNTING: 'FINANCE_ACCOUNTING',
  HUMAN_RESOURCES: 'HUMAN_RESOURCES',
  LAW: 'LAW',
  MARKETING: 'MARKETING',
  SALES: 'SALES',
} as const;

export type FieldOfStudy = (typeof FieldOfStudy)[keyof typeof FieldOfStudy];