export const Industry = {
  AEROSPACE: 'AEROSPACE',
  AGRICULTURE: 'AGRICULTURE',
  AUTOMOTIVE: 'AUTOMOTIVE',
  BANKING_INSURANCE: 'BANKING_INSURANCE',
  CONSTRUCTION: 'CONSTRUCTION',
  EDUCATION: 'EDUCATION',
  ENERGY: 'ENERGY',
  HEALTHCARE: 'HEALTHCARE',
  HOSPITALITY: 'HOSPITALITY',
  IT_SERVICES: 'IT_SERVICES',
  LUXURY: 'LUXURY',
  MANUFACTURING: 'MANUFACTURING',
  MEDIA_ENTERTAINMENT: 'MEDIA_ENTERTAINMENT',
  RETAIL: 'RETAIL',
  PUBLIC_SECTOR: 'PUBLIC_SECTOR',
  TRANSPORT_LOGISTICS: 'TRANSPORT_LOGISTICS',
} as const;

export type Industry = (typeof Industry)[keyof typeof Industry];